// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKFYl7f8Y9uIzumwavFfCSFaI_fPeFmMw',
    appId: '1:726203508641:web:686874951a93ecfe1b8de0',
    messagingSenderId: '726203508641',
    projectId: 'gpstore-user-app',
    authDomain: 'gpstore-user-app.firebaseapp.com',
    storageBucket: 'gpstore-user-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBty7g84mSDhaQAObAdICZMWDcl1qcF1-s',
    appId: '1:726203508641:android:2fecac1f554a1a9e1b8de0',
    messagingSenderId: '726203508641',
    projectId: 'gpstore-user-app',
    storageBucket: 'gpstore-user-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIcXxXKzVDKFujRlJWd_lqLfe4OBTMnos',
    appId: '1:726203508641:ios:4465b87c03c0a5511b8de0',
    messagingSenderId: '726203508641',
    projectId: 'gpstore-user-app',
    storageBucket: 'gpstore-user-app.appspot.com',
    androidClientId: '726203508641-ctsfo1v75k3ep825v7a4vivn5bj8pq3i.apps.googleusercontent.com',
    iosClientId: '726203508641-cgqk09d18vgbk9avnlheg7j7paosfob7.apps.googleusercontent.com',
    iosBundleId: 'com.gps.user',
  );
}
